name: "DLNA"
guid: "33EBA9CD-7DA1-4720-967F-DD7DAE7B74A1"
imageUrl: ""
version: 6
targetAbi: "10.10.3.0"
framework: "net8.0"
owner: "jellyfin"
overview: "DLNA Service"
description: >
  Adds DLNA capability to Jellyfin

category: "General"
artifacts:
  - "Jellyfin.Plugin.Dlna.dll"
  - "Jellyfin.Plugin.Dlna.Model.dll"
  - "Jellyfin.Plugin.Dlna.Playback.dll"
  - "Rssdp.dll"
changelog: |-
  - fix: add the icons to the compiled resources (#109) (#114) @FelixPetriconi
  - fix: adjusted typo in configuration page title (#112) @shindai
  - Only split user agent if it can be split (#95) @Shadowghost
